const SUCCESS = '_SUCCESS';
const ERROR = '_ERROR';

export const GET_LOCATION = 'SEARCH_LOCATION';
export const GET_LOCATION_SUCCESS = GET_LOCATION + SUCCESS;
export const GET_LOCATION_ERROR = GET_LOCATION + ERROR;

export const GET_FORECAST_BY_LOCATION = 'GET_FORECAST_BY_LOCATION';
export const GET_FORECAST_BY_LOCATION_SUCCESS = GET_FORECAST_BY_LOCATION + SUCCESS;
export const GET_FORECAST_BY_LOCATION_ERROR = GET_FORECAST_BY_LOCATION + ERROR;

export const GET_FORECAST_BY_GEO_POSITION = 'GET_FORECAST_BY_GEO_POSITION';
export const GET_FORECAST_BY_GEO_POSITION_SUCCESS = GET_FORECAST_BY_GEO_POSITION + SUCCESS;
export const GET_FORECAST_BY_GEO_POSITION_ERROR = GET_FORECAST_BY_GEO_POSITION + ERROR;

export const GET_GEO_POSITION = 'GET_GEO_POSITION';
export const GET_GEO_POSITION_SUCCESS = GET_GEO_POSITION + SUCCESS;
export const GET_GEO_POSITION_ERROR = GET_GEO_POSITION + ERROR;
